services:
  - type: web
    name: automaxpos-cloud
    env: node
    plan: starter
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: PGSSLMODE
        value: require
